In [1]:
import pandas as pd

In [4]:
gdp_all = pd.read_csv('gdp.tsv', sep='\t')

In [18]:
gdp_all

,"na_item,ppp_cat,geo\time",2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,"VI_PPS_EU28_HAB,GDP,AL",23,25,27,29,29,30,29,30,30,30,30,31
1,"VI_PPS_EU28_HAB,GDP,AT",125,125,127,126,128,132,131,130,129,128,127,127
2,"VI_PPS_EU28_HAB,GDP,BA",27,29,30,29,30,30,30,30,30,31,31,31
3,"VI_PPS_EU28_HAB,GDP,BE",117,115,118,120,119,121,120,119,118,118,116,115
4,"VI_PPS_EU28_HAB,GDP,BG",40,43,43,44,45,46,45,47,47,48,49,50
5,"VI_PPS_EU28_HAB,GDP,CH",156,158,160,159,162,164,165,165,165,160,156,157
6,"VI_PPS_EU28_HAB,GDP,CY",104,105,105,100,96,91,84,81,82,84,85,87
7,"VI_PPS_EU28_HAB,GDP,CZ",82,84,85,83,83,82,84,86,87,88,89,90
8,"VI_PPS_EU28_HAB,GDP,DE",117,117,117,120,123,124,124,126,124,124,124,123
9,"VI_PPS_EU28_HAB,GDP,DK",123,125,125,129,128,127,128,128,127,126,128,126
10,"VI_PPS_EU28_HAB,GDP,EA18",110,109,109,108,108,108,107,107,107,107,106,106
11,"VI_PPS_EU28_HAB,GDP,EA19",109,109,108,108,108,107,107,107,106,106,106,106
12,"VI_PPS_EU28_HAB,GDP,EE",69,68,63,65,71,74,75,77,76,77,79,81
13,"VI_PPS_EU28_HAB,GDP,EL",93,93,94,85,75,72,72,71,69,68,67,68
14,"VI_PPS_EU28_HAB,GDP,ES",103,101,100,96,92,91,89,90,91,91,92,91
15,"VI_PPS_EU28_HAB,GDP,EU27",100,100,100,100,100,100,100,100,100,100,100,100
16,"VI_PPS_EU28_HAB,GDP,EU28",100,100,100,100,100,100,100,100,100,100,100,100
17,"VI_PPS_EU28_HAB,GDP,FI",119,121,117,116,117,115,113,110,109,109,109,110
18,"VI_PPS_EU28_HAB,GDP,FR",108,106,108,108,108,107,108,107,106,104,104,104
19,"VI_PPS_EU28_HAB,GDP,HR",61,63,62,59,60,60,60,59,59,61,62,63
20,"VI_PPS_EU28_HAB,GDP,HU",60,63,64,65,66,66,67,68,68,67,68,70
21,"VI_PPS_EU28_HAB,GDP,IE",148,134,129,130,130,131,132,136,178,177,181,187
22,"VI_PPS_EU28_HAB,GDP,IS",130,130,130,119,117,119,121,122,126,130,130,133
23,"VI_PPS_EU28_HAB,GDP,IT",107,106,106,104,104,101,98,96,95,97,96,95
24,"VI_PPS_EU28_HAB,GDP,JP",109,105,103,105,103,106,107,104,104,102,99,98
25,"VI_PPS_EU28_HAB,GDP,LT",60,63,56,60,66,70,73,75,75,75,78,81
26,"VI_PPS_EU28_HAB,GDP,LU",265,262,255,257,265,260,261,269,266,260,253,254
27,"VI_PPS_EU28_HAB,GDP,LV",57,59,52,53,57,60,62,63,64,64,67,70
28,"VI_PPS_EU28_HAB,GDP,ME",39,42,40,41,42,39,41,41,42,44,45,47
29,"VI_PPS_EU28_HAB,GDP,MK",30,32,34,34,34,34,35,36,36,37,36,38
30,"VI_PPS_EU28_HAB,GDP,MT",79,79,81,83,82,84,85,89,93,95,98,98
31,"VI_PPS_EU28_HAB,GDP,NL",139,140,138,135,134,134,135,131,130,128,128,129
32,"VI_PPS_EU28_HAB,GDP,NO",177,187,172,174,179,186,184,176,156,145,146,150
33,"VI_PPS_EU28_HAB,GDP,PL",53,55,59,62,65,67,67,67,69,68,70,71
34,"VI_PPS_EU28_HAB,GDP,PT",81,81,82,82,77,75,76,77,77,77,77,76
35,"VI_PPS_EU28_HAB,GDP,RO",43,51,52,51,52,54,54,55,56,59,63,64
36,"VI_PPS_EU28_HAB,GDP,RS",35,38,39,38,40,40,40,39,39,39,39,40
37,"VI_PPS_EU28_HAB,GDP,SE",128,127,123,125,126,127,125,124,125,122,121,121
38,"VI_PPS_EU28_HAB,GDP,SI",87,90,85,83,83,82,82,82,82,83,85,87
39,"VI_PPS_EU28_HAB,GDP,SK",67,71,71,74,74,76,76,77,77,77,76,78
40,"VI_PPS_EU28_HAB,GDP,TR",47,48,48,52,56,58,61,64,66,65,66,65
41,"VI_PPS_EU28_HAB,GDP,UK",112,110,108,108,106,108,108,109,109,107,106,104
42,"VI_PPS_EU28_HAB,GDP,US",151,146,146,145,144,146,145,146,146,144,141,143

In [21]:
# I chose countries that lie near Poland:
# Germany, Austria, Poland, Czechia, Slovakia,
# Lithuania, Hungary, Romania
gdp = gdp_all.loc[[1, 7, 8, 20, 25, 33, 35, 39], :]
gdp

,"na_item,ppp_cat,geo\time",2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
1,"VI_PPS_EU28_HAB,GDP,AT",125,125,127,126,128,132,131,130,129,128,127,127
7,"VI_PPS_EU28_HAB,GDP,CZ",82,84,85,83,83,82,84,86,87,88,89,90
8,"VI_PPS_EU28_HAB,GDP,DE",117,117,117,120,123,124,124,126,124,124,124,123
20,"VI_PPS_EU28_HAB,GDP,HU",60,63,64,65,66,66,67,68,68,67,68,70
25,"VI_PPS_EU28_HAB,GDP,LT",60,63,56,60,66,70,73,75,75,75,78,81
33,"VI_PPS_EU28_HAB,GDP,PL",53,55,59,62,65,67,67,67,69,68,70,71
35,"VI_PPS_EU28_HAB,GDP,RO",43,51,52,51,52,54,54,55,56,59,63,64
39,"VI_PPS_EU28_HAB,GDP,SK",67,71,71,74,74,76,76,77,77,77,76,78

In [30]:
migrants_all = pd.read_csv('International-migrant-stock-at-mid-year.csv')

In [31]:
migrants_all

,Sort order,"Major area, region, country or area of destination",Notes,Code,Type of data (a),1990,1995,2000,2005,2010,2015,2019
0,225,EUROPE,NaN,917,NaN,49 608 231,53 489 829,56 858 788,63 594 822,70 678 025,75 008 219,82 304 539
1,226,Eastern Europe,NaN,923,NaN,21 995 312,21 344 124,20 435 785,19 744 557,19 110 686,19 841 537,20 278 745
2,227,Belarus,NaN,112,B,1 248 977,1 186 282,1 123 586,1 106 982,1 090 378,1 082 905,1 069 395
3,228,Bulgaria,NaN,100,B,21 510,32 435,43 360,61 074,76 287,123 803,168 516
4,229,Czechia,NaN,203,C,110 394,165 592,220 789,322 540,398 493,416 454,512 705
5,230,Hungary,NaN,348,B R,347 510,322 234,296 957,366 787,436 616,475 508,512 043
6,231,Poland,NaN,616,B,1 127 771,964 725,825 251,722 509,642 417,619 403,655 985
7,232,Republic of Moldova,18.0,498,B,544 162,367 231,247 828,171 122,129 488,106 374,104 713
8,233,Romania,NaN,642,B,135 825,135 037,134 254,145 162,177 211,281 048,462 552
9,234,Russian Federation,NaN,643,B,11 524 948,11 928 927,11 900 297,11 667 588,11 194 710,11 643 276,11 640 559
10,235,Slovakia,NaN,703,B,41 295,69 323,116 376,130 491,146 319,177 624,187 984
11,236,Ukraine,19.0,804,B,6 892 920,6 172 338,5 527 087,5 050 302,4 818 767,4 915 142,4 964 293
12,237,Northern Europe,NaN,924,NaN,6 645 605,7 194 824,7 900 973,9 588 814,11 344 850,13 269 401,15 094 924
13,238,Channel Islands,20.0,830,B,61 660,60 519,64 301,70 941,77 581,82 307,83 833
14,239,Denmark,NaN,208,B,235 189,303 108,371 026,440 383,500 772,595 876,722 878
15,240,Estonia,NaN,233,B,381 997,315 755,249 512,233 701,217 890,194 664,190 242
16,241,Faroe Islands,NaN,234,B,4 285,2 900,3 593,4 583,5 096,5 485,6 454
17,242,Finland,21.0,246,B,63 255,99 729,136 203,192 169,228 481,314 856,383 116
18,243,Iceland,NaN,352,B,9 584,12 738,15 892,25 492,35 091,39 072,52 404
19,244,Ireland,NaN,372,B,227 961,226 892,350 552,589 046,730 542,759 256,833 564
20,245,Isle of Man,NaN,833,B,34 769,36 886,39 002,41 475,43 447,42 238,42 864
21,246,Latvia,NaN,428,B,646 007,538 093,430 178,376 725,313 786,265 418,237 266
22,247,Lithuania,NaN,440,B,349 258,273 587,214 311,201 209,160 772,136 021,117 218
23,248,Norway,22.0,578,B,192 587,233 302,292 440,361 144,526 799,746 375,867 765
24,249,Sweden,NaN,752,B,788 767,936 022,1 003 798,1 125 790,1 384 929,1 676 264,2 005 210
25,250,United Kingdom,NaN,826,B,3 650 286,4 155 293,4 730 165,5 926 156,7 119 664,8 411 569,9 552 110
26,251,Southern Europe,NaN,925,NaN,4 340 439,6 230 116,7 681 653,12 004 009,16 206 134,15 815 447,16 503 552
27,252,Albania,NaN,8,B,66 013,71 354,76 695,64 739,52 784,52 031,49 160
28,253,Andorra,NaN,20,C,38 891,44 206,42 147,50 298,52 053,42 264,45 102
29,254,Bosnia and Herzegovina,NaN,70,I R,56 000,69 476,82 952,47 272,38 792,38 574,35 735
30,255,Croatia,NaN,191,B R,475 438,674 085,585 298,579 273,573 248,561 093,518 083
31,256,Gibraltar,NaN,292,B,8 709,8 381,8 054,9 211,10 369,11 065,11 172
32,257,Greece,NaN,300,B,618 139,857 850,1 111 665,1 190 707,1 321 149,1 242 924,1 211 382
33,258,Holy See,23.0,336,I,768,780,785,798,794,803,799
34,259,Italy,NaN,380,B,1 428 219,1 774 954,2 121 688,3 954 790,5 787 893,5 805 328,6 273 722
35,260,Malta,NaN,470,B,15 077,17 740,21 521,24 560,33 008,52 642,84 949
36,261,Montenegro,NaN,499,B,..,..,..,..,78 512,71 719,70 967
37,262,North Macedonia,NaN,807,B,95 142,109 343,125 665,127 667,129 701,130 730,131 175
38,263,Portugal,NaN,620,B,435 782,532 822,651 472,771 184,762 825,864 814,888 162
39,264,San Marino,NaN,674,C,3 310,3 659,4 045,4 218,4 880,5 195,5 507
40,265,Serbia,24.0,688,B,99 269,870 980,977 873,854 848,826 275,807 441,820 312
41,266,Slovenia,NaN,705,B,178 077,174 419,214 508,217 218,253 786,237 616,253 122
42,267,Spain,25.0,724,B,821 605,1 020 067,1 657 285,4 107 226,6 280 065,5 891 208,6 104 203
43,268,Western Europe,NaN,926,NaN,16 626 875,18 720 765,20 840 377,22 257 442,24 016 355,26 081 834,30 427 318
44,269,Austria,NaN,40,B,793 239,894 893,996 547,1 136 270,1 275 992,1 492 374,1 779 857
45,270,Belgium,NaN,56,B,1 280 583,1 288 003,1 268 368,1 248 733,1 503 806,1 783 488,1 981 919
46,271,France,NaN,250,B,5 897 267,6 087 993,6 278 718,6 737 600,7 309 986,7 874 172,8 334 875
47,272,Germany,NaN,276,B,5 936 181,7 464 406,8 992 631,9 402 447,9 812 263,10 220 418,13 132 146
48,273,Liechtenstein,NaN,438,B,10 906,13 311,15 483,18 898,22 342,23 799,25 467
49,274,Luxembourg,NaN,442,B,113 795,126 106,139 750,150 618,163 142,248 888,291 723
50,275,Monaco,NaN,492,B,20 359,21 060,21 787,21 312,21 132,25 983,26 511
51,276,Netherlands,NaN,528,B,1 182 263,1 346 164,1 556 337,1 736 127,1 832 510,1 996 318,2 282 791
52,277,Switzerland,NaN,756,B,1 392 282,1 478 829,1 570 756,1 805 437,2 075 182,2 416 394,2 572 029
53,280,Canada,NaN,124,B,4 333 318,4 864 778,5 511 914,6 078 985,6 761 226,7 428 657,7 960 657
54,281,Greenland,NaN,304,B,9 282,7 121,6 601,6 556,6 091,5 797,5 690
55,283,United States of America,NaN,840,B,23 251 026,28 451 053,34 814 053,39 258 293,44 183 643,48 178 877,50 661 149

In [32]:
migrants = migrants_all.loc[[4, 5, 6, 8, 10, 22, 44, 47], :]

In [33]:
migrants

,Sort order,"Major area, region, country or area of destination",Notes,Code,Type of data (a),1990,1995,2000,2005,2010,2015,2019
4,229,Czechia,NaN,203,C,110 394,165 592,220 789,322 540,398 493,416 454,512 705
5,230,Hungary,NaN,348,B R,347 510,322 234,296 957,366 787,436 616,475 508,512 043
6,231,Poland,NaN,616,B,1 127 771,964 725,825 251,722 509,642 417,619 403,655 985
8,233,Romania,NaN,642,B,135 825,135 037,134 254,145 162,177 211,281 048,462 552
10,235,Slovakia,NaN,703,B,41 295,69 323,116 376,130 491,146 319,177 624,187 984
22,247,Lithuania,NaN,440,B,349 258,273 587,214 311,201 209,160 772,136 021,117 218
44,269,Austria,NaN,40,B,793 239,894 893,996 547,1 136 270,1 275 992,1 492 374,1 779 857
47,272,Germany,NaN,276,B,5 936 181,7 464 406,8 992 631,9 402 447,9 812 263,10 220 418,13 132 146

So, in an extremely simple model, we have an equation in a form:
coeff[0] * gdp[2010] = migrants[2010]
coeff[0] * gdp[2015] = migrants[2015]
coeff[0] * gdp[2018] = migrants[2019]

and then we set coeff[0] to minimize squared errors
PLEASE NOTE THAT WE DON'T HAVE gdp data for 2019 year (only 2018)!

when we add another factor, e.g. underemployment it would look like this:
coeff[0] * gdp[2010] + coeff[1] * uempl[2010] = migrants[2010]
coeff[0] * gdp[2015] + coeff[1] * uempl[2015] = migrants[2015]
coeff[0] * gdp[2018] + coeff[1] * uempl[2018] = migrants[2019]
etc.